const state={selected:new Set(JSON.parse(localStorage.getItem('nomba-selected')||'[]')),notifications:{site:false,whatsapp:false,email:false},busy:false,lastSignal:null};
const $=id=>document.getElementById(id); const API=window.NOMBA_API||localStorage.getItem('nomba-api')||'';
const categoryFor=n=>{if(n<=49)return'Indicators & Breakouts';if(n<=93)return'Price Action & Patterns';if(n<=103)return'Indicators';if(n<=123)return'Arbitrage';if(n<=159)return'Options & Crypto';if(n<=193)return'Macro & Smart Money';if(n<=260)return'Quant & Indicators';if(n<=330)return'Advanced Indicators';if(n<=370)return'Wyckoff & Patterns';if(n<=420)return'Breadth & Arbitrage';if(n<=500)return'Options & Macro';return'Extended Library'};
STRATEGIES.forEach(s=>s.category=categoryFor(s.id)); const categories=[...new Set(STRATEGIES.map(s=>s.category))];categories.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;$('category').appendChild(o)});
function visible(){const q=$('search').value.toLowerCase(),cat=$('category').value;return STRATEGIES.filter(s=>(!q||s.name.toLowerCase().includes(q)||String(s.id).includes(q))&&(cat==='all'||s.category===cat))}
function render(){const list=visible();$('resultCount').textContent=`${list.length.toLocaleString()} strategies`;$('strategyGrid').innerHTML=list.map(s=>`<div class="strategy ${state.selected.has(s.id)?'selected':''}" data-id="${s.id}" role="button" tabindex="0" aria-pressed="${state.selected.has(s.id)}"><span class="strategy-id">#${String(s.id).padStart(4,'0')}</span><span class="strategy-name">${s.name}</span></div>`).join('');document.querySelectorAll('.strategy').forEach(el=>{const choose=()=>{const id=+el.dataset.id;state.selected.has(id)?state.selected.delete(id):state.selected.add(id);save();render();requestSignal()};el.onclick=choose;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose()}}});$('selectedCount').textContent=state.selected.size.toLocaleString()}
function save(){localStorage.setItem('nomba-selected',JSON.stringify([...state.selected]))}
function preview(){const n=state.selected.size;if(!n){setSignal('WAIT','Select strategies to begin',0);setVotes(0,0,0,0);return}const t=Math.floor(Date.now()/300000);const buy=(n*37+t)%n,sell=(n*23+t*2)%n,neutral=Math.max(0,Math.floor(n*.12)),uncertain=Math.max(0,Math.floor(n*.03));const total=Math.max(1,buy+sell+neutral+uncertain),b=Math.round(buy/total*100),s=Math.round(sell/total*100);const sig=b>s?'BUY':s>b?'SELL':'WAIT',conf=Math.max(50,Math.min(96,Math.max(b,s)));setVotes(buy,sell,neutral,uncertain);setSignal(sig,`${n.toLocaleString()} selected strategies • local preview`,conf);setTF(sig,b>=s?'BUY':'SELL',Math.abs(b-s)>8?(b>s?'BUY':'SELL'):'WAIT')}
function setVotes(b,s,n,u){$('buy').textContent=b;$('sell').textContent=s;$('neutral').textContent=n;$('uncertain').textContent=u}
function setSignal(sig,msg,conf){$('signal').innerHTML=`<strong>${sig}</strong><span>${msg}</span>`;$('confidence').textContent=conf+'%';$('meterFill').style.width=conf+'%'} function setTF(a,b,c){$('tf5').textContent=a;$('tf15').textContent=b;$('tf30').textContent=c}
async function routeNotification(signal){if(!signal||signal==='WAIT')return;const payload={channel_preferences:Object.keys(state.notifications).filter(k=>state.notifications[k]),symbol:$('symbol').value,signal,confidence:$('confidence').textContent,price:$('price').textContent,timestamp:new Date().toISOString()};if(state.notifications.site&&'Notification'in window){if(Notification.permission==='granted')new Notification(`Nomba1BOT ${signal}`,{body:`${payload.symbol} • ${payload.confidence} confidence`});else if(Notification.permission!=='denied')await Notification.requestPermission()}if((state.notifications.email||state.notifications.whatsapp)&&API){try{await fetch(API.replace(/\/$/,'')+'/notifications/dispatch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}catch(e){console.warn('Notification dispatch unavailable',e)}}}
async function requestSignal(){preview();if(!API||!state.selected.size)return;state.busy=true;$('statusText').textContent='Reading live market source…';try{const r=await fetch(API.replace(/\/$/,'')+'/signal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol:$('symbol').value,strategies:[...state.selected],timeframes:['5m','15m','30m']})});if(!r.ok)throw new Error('Signal engine unavailable');const d=await r.json();setVotes(d.votes?.BUY||0,d.votes?.SELL||0,d.votes?.NEUTRAL||0,d.votes?.UNCERTAIN||0);setSignal(d.signal||'WAIT',`${state.selected.size.toLocaleString()} selected • ${d.data_status||'live market-data'}`,d.confidence||0);setTF(d.timeframes?.['5m']?.signal||'WAIT',d.timeframes?.['15m']?.signal||'WAIT',d.timeframes?.['30m']?.signal||'WAIT');if(d.price!==null&&d.price!==undefined)$('price').textContent=Number(d.price).toLocaleString(undefined,{maximumFractionDigits:6});$('marketName').textContent=$('symbol').value+' • LIVE market data';$('statusText').textContent='LIVE source connected';$('dot').style.background='var(--green)';if(d.signal!==state.lastSignal){state.lastSignal=d.signal;routeNotification(d.signal)}}catch(e){$('statusText').textContent=API?'LIVE source unavailable • local preview':'Local preview mode';$('dot').style.background='var(--yellow)'}finally{state.busy=false}}
function toggleNotification(kind,id,label){state.notifications[kind]=!state.notifications[kind];$(id).textContent=`${label}: ${state.notifications[kind]?'ON':'OFF'}`;$(id).classList.toggle('active',state.notifications[kind]);if(kind==='site'&&state.notifications.site&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission()}
function tick(){const sec=60-Math.floor(Date.now()/1000)%60;const m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');$('nextRun').textContent=`${m}:${s}`}
$('search').oninput=render;$('category').onchange=render;$('selectAll').onclick=()=>{visible().forEach(s=>state.selected.add(s.id));save();render();requestSignal()};$('clearAll').onclick=()=>{state.selected.clear();save();render();requestSignal()};$('notifySite').onclick=()=>toggleNotification('site','notifySite','Site notifications');$('notifyWhatsApp').onclick=()=>toggleNotification('whatsapp','notifyWhatsApp','WhatsApp');$('notifyEmail').onclick=()=>toggleNotification('email','notifyEmail','Email');$('symbol').onchange=()=>{$('marketName').textContent=$('symbol').value+' • LIVE market data';requestSignal()};
$('statusText').textContent=API?'Connecting to LIVE source…':`${STRATEGIES.length.toLocaleString()} strategies ready • local preview`;$('dot').style.background='var(--yellow)';render();preview();requestSignal();setInterval(tick,1000);setInterval(()=>{if(state.selected.size)requestSignal()},60000);