const state={selected:new Set(JSON.parse(localStorage.getItem('nomba-selected')||'[]')),notifications:{site:false,whatsapp:false,email:false},busy:false,lastSignal:null};
const $=id=>document.getElementById(id);const API=window.NOMBA_API||localStorage.getItem('nomba-api')||'';const TFS=['1m','5m','15m','30m','1h','4h'];
const categoryFor=n=>{if(n<=49)return'Indicators & Breakouts';if(n<=93)return'Price Action & Patterns';if(n<=103)return'Indicators';if(n<=123)return'Arbitrage';if(n<=159)return'Options & Crypto';if(n<=193)return'Macro & Smart Money';if(n<=260)return'Quant & Indicators';if(n<=330)return'Advanced Indicators';if(n<=370)return'Wyckoff & Patterns';if(n<=420)return'Breadth & Arbitrage';if(n<=500)return'Options & Macro';return'Extended Library'};
STRATEGIES.forEach(s=>s.category=categoryFor(s.id));const categories=[...new Set(STRATEGIES.map(s=>s.category))];categories.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;$('category').appendChild(o)});
function visible(){const q=$('search').value.toLowerCase(),cat=$('category').value;return STRATEGIES.filter(s=>(!q||s.name.toLowerCase().includes(q)||String(s.id).includes(q))&&(cat==='all'||s.category===cat))}
function render(){const list=visible();$('resultCount').textContent=`${list.length.toLocaleString()} strategies`;$('strategyGrid').innerHTML=list.map(s=>`<div class="strategy ${state.selected.has(s.id)?'selected':''}" data-id="${s.id}" role="button" tabindex="0" aria-pressed="${state.selected.has(s.id)}"><span class="strategy-id">#${String(s.id).padStart(4,'0')}</span><span class="strategy-name">${s.name}</span></div>`).join('');document.querySelectorAll('.strategy').forEach(el=>{const choose=()=>{const id=+el.dataset.id;state.selected.has(id)?state.selected.delete(id):state.selected.add(id);save();render();requestSignal()};el.onclick=choose;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose()}}});$('selectedCount').textContent=state.selected.size.toLocaleString()}
function save(){localStorage.setItem('nomba-selected',JSON.stringify([...state.selected]))}
function preview(){if(!state.selected.size){setSignal('WAIT','Select strategies to begin',0);setVotes(0,0,0,0);return}setSignal('WAIT',`${state.selected.size.toLocaleString()} selected • connecting to LIVE engine`,0);setVotes(0,0,0,0);setTF('WAIT','WAIT','WAIT','WAIT','WAIT','WAIT')}
function setVotes(b,s,n,u){$('buy').textContent=b;$('sell').textContent=s;$('neutral').textContent=n;$('uncertain').textContent=u}
function setSignal(sig,msg,conf){$('signal').innerHTML=`<strong>${sig}</strong><span>${msg}</span>`;$('confidence').textContent=conf+'%';$('meterFill').style.width=conf+'%'}
function setTF(...vals){TFS.forEach((tf,i)=>{const el=$('tf'+tf);if(el)el.textContent=vals[i]||'WAIT'})}
function toast(title,body,kind='info'){const box=$('toastBox');if(!box)return;const e=document.createElement('div');e.className=`toast ${kind}`;e.innerHTML=`<b>${title}</b><span>${body}</span>`;box.appendChild(e);setTimeout(()=>e.remove(),6500)}
async function routeNotification(signal){if(!signal||signal==='WAIT')return;const p={channel_preferences:Object.keys(state.notifications).filter(k=>state.notifications[k]),symbol:$('symbol').value,signal,confidence:$('confidence').textContent,price:$('price').textContent,timestamp:new Date().toISOString(),recipient_email:$('emailTarget')?.value.trim()||localStorage.getItem('nomba-email')||'',recipient_whatsapp:$('whatsappTarget')?.value.trim()||localStorage.getItem('nomba-whatsapp')||''};if(state.notifications.site){toast(`Nomba1BOT • ${signal}`,`${p.symbol} • ${p.confidence} confidence`,'signal');if('Notification'in window&&Notification.permission==='granted')new Notification(`Nomba1BOT ${signal}`,{body:`${p.symbol} • ${p.confidence} confidence`});else if('Notification'in window&&Notification.permission==='default')Notification.requestPermission()}if((state.notifications.email||state.notifications.whatsapp)&&API){try{const r=await fetch(API.replace(/\/$/,'')+'/notifications/dispatch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();(d.channels||[]).forEach(x=>toast(x.channel,x.status==='sent'?'Notification sent':'Not configured / provider error',x.status==='sent'?'signal':'error'))}catch(e){toast('Notifications','Backend notification service unavailable','error')}}}
async function requestSignal(){preview();if(!API||!state.selected.size)return;state.busy=true;$('statusText').textContent='Reading LIVE market source…';try{const r=await fetch(API.replace(/\/$/,'')+'/signal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol:$('symbol').value,strategies:[...state.selected].map(id=>STRATEGIES.find(s=>s.id===id)).filter(Boolean),timeframes:TFS})});if(!r.ok)throw new Error('Signal engine unavailable');const d=await r.json();setVotes(d.votes?.BUY||0,d.votes?.SELL||0,d.votes?.NEUTRAL||0,d.votes?.UNCERTAIN||0);setSignal(d.signal||'WAIT',`${state.selected.size.toLocaleString()} selected • ${d.data_status||'LIVE market data'}`,d.confidence||0);setTF(d.timeframes?.['1m']?.signal,d.timeframes?.['5m']?.signal,d.timeframes?.['15m']?.signal,d.timeframes?.['30m']?.signal,d.timeframes?.['1h']?.signal,d.timeframes?.['4h']?.signal);if(d.price!=null)$('price').textContent=Number(d.price).toLocaleString(undefined,{maximumFractionDigits:6});$('marketName').textContent=$('symbol').value+' • LIVE market data';$('statusText').textContent='LIVE source connected';$('dot').style.background='var(--green)';if(d.signal!==state.lastSignal){state.lastSignal=d.signal;routeNotification(d.signal)}}catch(e){$('statusText').textContent=API?'LIVE source unavailable':'Local preview mode';$('dot').style.background='var(--yellow)';toast('Market engine','Unable to reach the LIVE source','error')}finally{state.busy=false}}
function toggleNotification(kind,id,label){state.notifications[kind]=!state.notifications[kind];$(id).textContent=`${label}: ${state.notifications[kind]?'ON':'OFF'}`;$(id).classList.toggle('active',state.notifications[kind]);if(kind==='site'&&state.notifications.site&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission();if(kind!=='site'&&state.notifications[kind])toast(label,'Recipient ready. Provider configuration is still required for external delivery.','info')}
function tick(){const sec=60-Math.floor(Date.now()/1000)%60;$('nextRun').textContent=`00:${String(sec).padStart(2,'0')}`}
$('search').oninput=render;$('category').onchange=render;$('selectAll').onclick=()=>{visible().forEach(s=>state.selected.add(s.id));save();render();requestSignal()};$('clearAll').onclick=()=>{state.selected.clear();save();render();requestSignal()};$('notifySite').onclick=()=>toggleNotification('site','notifySite','Site notifications');$('notifyWhatsApp').onclick=()=>toggleNotification('whatsapp','notifyWhatsApp','WhatsApp');$('notifyEmail').onclick=()=>toggleNotification('email','notifyEmail','Email');$('emailTarget').onchange=e=>localStorage.setItem('nomba-email',e.target.value.trim());$('whatsappTarget').onchange=e=>localStorage.setItem('nomba-whatsapp',e.target.value.trim());$('symbol').onchange=()=>{$('marketName').textContent=$('symbol').value+' • LIVE market data';state.lastSignal=null;requestSignal()};
$('statusText').textContent=API?'Connecting to LIVE source…':`${STRATEGIES.length.toLocaleString()} strategies ready • local preview`;$('dot').style.background='var(--yellow)';render();preview();requestSignal();setInterval(tick,1000);setInterval(()=>{if(state.selected.size)requestSignal()},60000);