const state={selected:new Set(JSON.parse(localStorage.getItem('nomba-selected')||'[]')),notifications:false};
const $=id=>document.getElementById(id);
const categoryFor=n=>{if(n<=49)return'Indicators & Breakouts';if(n<=93)return'Price Action & Patterns';if(n<=103)return'Indicators';if(n<=123)return'Arbitrage';if(n<=159)return'Options & Crypto';if(n<=193)return'Macro & Smart Money';if(n<=260)return'Quant & Indicators';if(n<=330)return'Advanced Indicators';if(n<=370)return'Wyckoff & Patterns';if(n<=420)return'Breadth & Arbitrage';if(n<=500)return'Options & Macro';return'Other'};
STRATEGIES.forEach(s=>s.category=categoryFor(s.id));
const categories=[...new Set(STRATEGIES.map(s=>s.category))];categories.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;$('category').appendChild(o)});
function render(){const q=$('search').value.toLowerCase(),cat=$('category').value;const list=STRATEGIES.filter(s=>(!q||s.name.toLowerCase().includes(q)||String(s.id).includes(q))&&(cat==='all'||s.category===cat));$('resultCount').textContent=`${list.length} strategies`;$('strategyGrid').innerHTML=list.map(s=>`<div class="strategy ${state.selected.has(s.id)?'on':''}" data-id="${s.id}"><span class="num">#${String(s.id).padStart(3,'0')}</span><b>${s.name}</b></div>`).join('');document.querySelectorAll('.strategy').forEach(el=>el.onclick=()=>{const id=+el.dataset.id;state.selected.has(id)?state.selected.delete(id):state.selected.add(id);save();render();updateSignal()});$('selectedCount').textContent=state.selected.size}
function save(){localStorage.setItem('nomba-selected',JSON.stringify([...state.selected]))}
function updateSignal(){const n=state.selected.size;if(!n){['buy','sell','neutral','uncertain'].forEach(x=>$(x).textContent='0');$('signal').innerHTML='<strong>WAIT</strong><span>Select strategies to begin</span>';$('confidence').textContent='0%';$('meterFill').style.width='0';return}const t=Math.floor(Date.now()/300000);const buy=(n*37+t)%n,sell=(n*23+t*2)%n,neutral=Math.max(0,Math.floor(n*.12)),uncertain=Math.max(0,Math.floor(n*.03));const total=Math.max(1,buy+sell+neutral+uncertain),b=Math.round(buy/total*100),s=Math.round(sell/total*100);let signal=b>s?'BUY':s>b?'SELL':'WAIT',conf=Math.max(50,Math.min(96,Math.max(b,s)));$('buy').textContent=buy;$('sell').textContent=sell;$('neutral').textContent=neutral;$('uncertain').textContent=uncertain;$('signal').innerHTML=`<strong>${signal}</strong><span>${n} selected strategies • aggregated preview</span>`;$('confidence').textContent=conf+'%';$('meterFill').style.width=conf+'%';['tf5','tf15','tf30'].forEach((id,i)=>$(id).textContent=i===0?signal:(i===1?(b>=s?'BUY':'SELL'):(Math.abs(b-s)>8?(b>s?'BUY':'SELL'):'WAIT')))}
function tick(){const sec=300-Math.floor(Date.now()/1000)%300;const m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');$('nextRun').textContent=`${m}:${s}`;updateSignal()}
$('search').oninput=render;$('category').onchange=render;$('selectAll').onclick=()=>{const q=$('search').value.toLowerCase(),cat=$('category').value;STRATEGIES.filter(s=>(!q||s.name.toLowerCase().includes(q)||String(s.id).includes(q))&&(cat==='all'||s.category===cat)).forEach(s=>state.selected.add(s.id));save();render();updateSignal()};$('clearAll').onclick=()=>{state.selected.clear();save();render();updateSignal()};$('notify').onclick=()=>{state.notifications=!state.notifications;$('notify').textContent='WhatsApp notifications: '+(state.notifications?'ON':'OFF');$('notify').classList.toggle('active',state.notifications)};$('symbol').onchange=()=>{$('marketName').textContent=$('symbol').value+' • demo feed'};
$('statusText').textContent='Dashboard ready';$('dot').style.background='var(--green)';render();updateSignal();setInterval(tick,1000);
